### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by Sir-Death** [thuml/TransNorm#2]
Hi,I would like to know how to do the channel visualization in the paper. Could you please share the code? Thank you very much

**Comment by wxm17** [comment]
[vis.py.zip](https://github.com/thuml/TransNorm/files/5534229/vis.py.zip)

Sure. Please kindly find the source code of channel visualization in the attachment.

**Comment by Sir-Death** [comment]
Thank you very much

**Comment by Sir-Death** [comment]
Sorry to bother you again, but I want to know how to get feature map in the source code

**Comment by wxm17** [comment]
<img width="443" alt="屏幕快照 2020-11-13 16 26 28" src="https://user-images.githubusercontent.com/20165494/99046026-24272280-25cd-11eb-8e57-f06504d04f09.png">

You can simply edit the code of the forward function of ResNet and return the feature maps of all channels. For example, in the **feature_maps** here in the attachment has a size of [N, 64, 112, 112]. After that, you can select the specific channel you would like to visualize in the main function by **feature_map = feature_maps[image_index, channel_index, :, :]**.

**Comment by Sir-Death** [comment]
Thank you very much for your patience. I have solved it.
